[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
food_gathering = "EudLu51y9mdaTC5tWdGpptLocsfQimz3ZCyvcfA7DbRa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
