[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
food_gathering = "HL1wZTiWUiqzdfSANMd5b7TGcDr6FVA13RF4SdrDUaiQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
